---
exclude: ^tests/test_data/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json$|\.ipynb$
      - id: requirements-txt-fixer
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ^tests/helpers\.py$
      - id: check-merge-conflict
  - repo: https://github.com/jsh9/muff-pre-commit
    rev: 0.13.2
    hooks:
      - id: muff-format
        args: [--config, muff.toml]
  - repo: https://github.com/jsh9/blank-line-after-blocks
    rev: 0.1.4
    hooks:
      - id: blank-line-after-blocks
      - id: blank-line-after-blocks-jupyter
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.18.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        args:
          - --in-place
          - --sort-table-keys
          - --sort-inline-tables
          - --sort-first=name,version,dependencies,requires-python,authors,maintainers
          - --trailing-comma-inline-array
          - --sort-inline-arrays
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args: [--wrap=79, --number]
        additional_dependencies: [mdformat-gfm]
  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.1.0
    hooks:
      - id: markdown-toc-creator
        exclude: ^AGENTS\.md$|^CHANGELOG\.md$
  - repo: https://github.com/jsh9/markdown-heading-numbering
    rev: 0.1.0
    hooks:
      - id: markdown-heading-numbering
        exclude: ^CHANGELOG\.md$
  - repo: local
    hooks:
      - id: ensure-pretty-format-json-upstream
        name: Ensure upstream pretty_format_json.py is unchanged
        language: system
        entry: python .pre_commit_hook_script/ensure_pretty_format_json_commit.py
        pass_filenames: false
